/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as VersesRouteImport } from './routes/verses'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as MapRouteImport } from './routes/map'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfessionRouteImport } from './routes/confession'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BarrierefreiheitRouteImport } from './routes/barrierefreiheit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const VersesRoute = VersesRouteImport.update({
  id: '/verses',
  path: '/verses',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionRoute = ConfessionRouteImport.update({
  id: '/confession',
  path: '/confession',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BarrierefreiheitRoute = BarrierefreiheitRouteImport.update({
  id: '/barrierefreiheit',
  path: '/barrierefreiheit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/books': typeof BooksRoute
  '/confession': typeof ConfessionRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gallery': typeof GalleryRoute
  '/impressum': typeof ImpressumRoute
  '/index': typeof Char91indexChar93Route
  '/map': typeof MapRoute
  '/sermons': typeof SermonsRoute
  '/services': typeof ServicesRoute
  '/verses': typeof VersesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/books': typeof BooksRoute
  '/confession': typeof ConfessionRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gallery': typeof GalleryRoute
  '/impressum': typeof ImpressumRoute
  '/index': typeof Char91indexChar93Route
  '/map': typeof MapRoute
  '/sermons': typeof SermonsRoute
  '/services': typeof ServicesRoute
  '/verses': typeof VersesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/barrierefreiheit': typeof BarrierefreiheitRoute
  '/books': typeof BooksRoute
  '/confession': typeof ConfessionRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/gallery': typeof GalleryRoute
  '/impressum': typeof ImpressumRoute
  '/index': typeof Char91indexChar93Route
  '/map': typeof MapRoute
  '/sermons': typeof SermonsRoute
  '/services': typeof ServicesRoute
  '/verses': typeof VersesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/barrierefreiheit'
    | '/books'
    | '/confession'
    | '/contact'
    | '/datenschutz'
    | '/gallery'
    | '/impressum'
    | '/index'
    | '/map'
    | '/sermons'
    | '/services'
    | '/verses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/barrierefreiheit'
    | '/books'
    | '/confession'
    | '/contact'
    | '/datenschutz'
    | '/gallery'
    | '/impressum'
    | '/index'
    | '/map'
    | '/sermons'
    | '/services'
    | '/verses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/barrierefreiheit'
    | '/books'
    | '/confession'
    | '/contact'
    | '/datenschutz'
    | '/gallery'
    | '/impressum'
    | '/index'
    | '/map'
    | '/sermons'
    | '/services'
    | '/verses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BarrierefreiheitRoute: typeof BarrierefreiheitRoute
  BooksRoute: typeof BooksRoute
  ConfessionRoute: typeof ConfessionRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  GalleryRoute: typeof GalleryRoute
  ImpressumRoute: typeof ImpressumRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  MapRoute: typeof MapRoute
  SermonsRoute: typeof SermonsRoute
  ServicesRoute: typeof ServicesRoute
  VersesRoute: typeof VersesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verses': {
      id: '/verses'
      path: '/verses'
      fullPath: '/verses'
      preLoaderRoute: typeof VersesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confession': {
      id: '/confession'
      path: '/confession'
      fullPath: '/confession'
      preLoaderRoute: typeof ConfessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barrierefreiheit': {
      id: '/barrierefreiheit'
      path: '/barrierefreiheit'
      fullPath: '/barrierefreiheit'
      preLoaderRoute: typeof BarrierefreiheitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BarrierefreiheitRoute: BarrierefreiheitRoute,
  BooksRoute: BooksRoute,
  ConfessionRoute: ConfessionRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  GalleryRoute: GalleryRoute,
  ImpressumRoute: ImpressumRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  MapRoute: MapRoute,
  SermonsRoute: SermonsRoute,
  ServicesRoute: ServicesRoute,
  VersesRoute: VersesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
